apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sandboard.fullname" . }}
  labels:
    {{- include "sandboard.labels" . | nindent 4 }}
    {{- include "sandboard.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sandboard.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sandboard.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: sandboard
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: SANDBOARD_BIND_ADDR
              value: "0.0.0.0"
            - name: SANDBOARD_PORT
              value: {{ .Values.service.port | quote }}
            - name: SANDBOARD_PUBLIC_URL
              value: {{ .Values.ingress.publicUrl | quote }}
            - name: SANDBOARD_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "sandboard.secretName" . }}
                  key: database-url
            - name: SANDBOARD_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "sandboard.secretName" . }}
                  key: master-key
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
